In [1]:
import pandas as pd

In [10]:
df = pd.read_csv('/Users/apple/Documents/Python/datasets/vt_tax_data_2016.tsv', sep = ',')

In [9]:
df.head()

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,PREP,N2,...,N10300,A10300,N85530,A85530,N85300,A85300,N11901,A11901,N11902,A11902
0,50,VT,0,1,111580,85090,14170,10740,45360,130630,...,53660,50699,0,0,0,0,10820,9734,88260,138337
1,50,VT,0,2,82760,51960,18820,11310,35600,132950,...,74340,221146,0,0,0,0,12820,20029,68760,151729
2,50,VT,0,3,46270,19540,22650,3620,24140,91870,...,44860,266097,0,0,0,0,10810,24499,34600,90583
3,50,VT,0,4,30070,5830,22190,960,16060,71610,...,29580,264678,0,0,0,0,7320,21573,21300,67045
4,50,VT,0,5,39530,3900,33800,590,22500,103710,...,39170,731963,40,24,0,0,12500,67761,23320,103034

In [11]:
df.columns

Index(['STATEFIPS', 'STATE', 'zipcode', 'agi_stub', 'N1', 'mars1', 'MARS2',
       'MARS4', 'PREP', 'N2',
       ...
       'N10300', 'A10300', 'N85530', 'A85530', 'N85300', 'A85300', 'N11901',
       'A11901', 'N11902', 'A11902'],
      dtype='object', length=147)

# Limiting what you want to load

In [12]:
#limiting columns 

cols = ['STATEFIPS', 'STATE', 'zipcode', 'agi_stub', 'N1' ] # we can also use [1,2,3,4,5]
data = pd.read_csv('/Users/apple/Documents/Python/datasets/vt_tax_data_2016.tsv',usecols = cols)
data.head(3)

   STATEFIPS STATE  zipcode  agi_stub      N1
0         50    VT        0         1  111580
1         50    VT        0         2   82760
2         50    VT        0         3   46270

In [15]:
data.shape

(1476, 5)

In [17]:
#limiting rows
# getting first 100 rows
data_r = pd.read_csv('/Users/apple/Documents/Python/datasets/vt_tax_data_2016.tsv',usecols = cols, nrows = 100)
data_r.shape

(100, 5)

In [19]:
#With this we can also skiprows: skips the first n rows you mention
#use header = none when using this.. so that pandas knows there is no header
next_dt = pd.read_csv('/Users/apple/Documents/Python/datasets/vt_tax_data_2016.tsv', nrows = 100, skiprows = 100,
                     header = None)
next_dt.head(5)

,0,1,2,3,4,5,6,7,8,9,...,137,138,139,140,141,142,143,144,145,146
0,50,VT,5046,4,60,0,50,0,40,150,...,60,515,0,0,0,0,20,113,40,166
1,50,VT,5046,5,50,0,50,0,30,150,...,50,1045,0,0,0,0,0,0,30,119
2,50,VT,5046,6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,50,VT,5048,1,390,300,50,40,150,410,...,190,213,0,0,0,0,50,45,300,430
4,50,VT,5048,2,350,220,70,50,130,520,...,320,969,0,0,0,0,60,105,280,563

In [24]:
# how to assign columns : either create a manual list or take it from existing data frame
col1 = list(df) #col1 has the columns from df dataframe
next_dt1 = pd.read_csv('/Users/apple/Documents/Python/datasets/vt_tax_data_2016.tsv', nrows = 100, skiprows = 100,
                     header = None, names = col1)
next_dt1.head(5)

,STATEFIPS,STATE,zipcode,agi_stub,N1,mars1,MARS2,MARS4,PREP,N2,...,N10300,A10300,N85530,A85530,N85300,A85300,N11901,A11901,N11902,A11902
0,50,VT,5046,4,60,0,50,0,40,150,...,60,515,0,0,0,0,20,113,40,166
1,50,VT,5046,5,50,0,50,0,30,150,...,50,1045,0,0,0,0,0,0,30,119
2,50,VT,5046,6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,50,VT,5048,1,390,300,50,40,150,410,...,190,213,0,0,0,0,50,45,300,430
4,50,VT,5048,2,350,220,70,50,130,520,...,320,969,0,0,0,0,60,105,280,563

# Handling errors & missing data while loading in data_frame 

using read_csv

In [29]:
#pandas infer data types automatically 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1476 entries, 0 to 1475
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   STATEFIPS  1476 non-null   int64
 1   STATE      1476 non-null   object
 2   zipcode    1476 non-null   int64
 3   agi_stub   1476 non-null   int64
 4   N1         1476 non-null   int64
dtypes: int64(4), object(1)
memory usage: 57.8+ KB

In [33]:
#or
data.dtypes

STATEFIPS      int64
STATE         object
zipcode      float64
agi_stub       int64
N1             int64
dtype: object

In [30]:
#suppose you want to change zipcode to str type
# use dtype - pass as dict {"column_name": type}

cols = ['STATEFIPS', 'STATE', 'zipcode', 'agi_stub', 'N1' ] # we can also use [1,2,3,4,5]
data = pd.read_csv('/Users/apple/Documents/Python/datasets/vt_tax_data_2016.tsv',usecols = cols, dtype = {"zipcode": str})
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1476 entries, 0 to 1475
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   STATEFIPS  1476 non-null   int64
 1   STATE      1476 non-null   object
 2   zipcode    1476 non-null   object
 3   agi_stub   1476 non-null   int64
 4   N1         1476 non-null   int64
dtypes: int64(3), object(2)
memory usage: 57.8+ KB

In [35]:
data_types = {"agi_stub": "category",
              "zipcode": str}

# Load csv using dtype to set correct data types
data = pd.read_csv("/Users/apple/Documents/Python/datasets/vt_tax_data_2016.tsv", dtype = data_types)

# Print data types of resulting frame
print(data.dtypes.head())

STATEFIPS       int64
STATE          object
zipcode        object
agi_stub     category
N1              int64
dtype: object

In [31]:
#pandas interprets missing value as NA or Null 

# na_values accepts single val, list, dict 
# anything 0 empty just a invalid charater - will be converted to NA

data.sort_values('zipcode')

      STATEFIPS STATE zipcode  agi_stub      N1
0            50    VT       0         1  111580
1            50    VT       0         2   82760
2            50    VT       0         3   46270
3            50    VT       0         4   30070
4            50    VT       0         5   39530
...         ...   ...     ...       ...     ...
1470         50    VT   99999         1    2710
1471         50    VT   99999         2    2010
1472         50    VT   99999         3    1070
1473         50    VT   99999         4     650
1475         50    VT   99999         6     180

[1476 rows x 5 columns]

In [32]:
#handling 0's before loading data 
# where ever its 0 itll be now null
cols = ['STATEFIPS', 'STATE', 'zipcode', 'agi_stub', 'N1' ] # we can also use [1,2,3,4,5]
data = pd.read_csv('/Users/apple/Documents/Python/datasets/vt_tax_data_2016.tsv',usecols = cols, na_values = {"zipcode": 0})
data[data['zipcode'].isna()]

   STATEFIPS STATE  zipcode  agi_stub      N1
0         50    VT      NaN         1  111580
1         50    VT      NaN         2   82760
2         50    VT      NaN         3   46270
3         50    VT      NaN         4   30070
4         50    VT      NaN         5   39530
5         50    VT      NaN         6    9620

In [ ]:
#Line pandas cannot pass
# error_bad_lines = False -- skips unparseable records
# warn_bad_line = True -- shows message when records are skipped

try:
  # Set warn_bad_lines to issue warnings about bad records
  data = pd.read_csv("vt_tax_data_2016_corrupt.csv", 
                     error_bad_lines=False, 
                     warn_bad_lines=True)
  
  # View first 5 records
  print(data.head())
  
except pd.errors.ParserError:
    print("Your data contained rows that could not be parsed.")